<?php

use Illuminate\Database\Seeder;

class UnidadeCurricularTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->command->info("UnidadeCurricular seeder - Start");

        $faker = Faker\Factory::create('pt_PT');
        $disciplinas = [
            'Análise Matemática',
            'Álgebra Linear',
            'Física Aplicada',
            'Programação I',
            'Sistemas Computacionais',
            'Matemática Discreta',
            'Estatística',
            'Programação II',
            'Tecnologias de Internet',
            'Sistemas Operativos',
            'Inglês',
            'Sistemas Gráficos e Interação',
            'Algoritmos e Estruturas de Dados',
            'Bases de Dados',
            'Redes de Computadores',
            'Programação Avançada',
            'Aplicações para a Internet',
            'Engenharia de Software',
            'Inteligência Artificial',
            'Sistemas de Bases de Dados',
            'Segurança da Informação',
            'Tecnologias de Virtualização',
            'Redes de Dados',
            'Administração de Sistemas',
            'Desenvolvimento de Aplicações Distribuídas',
            'Integração de Sistemas',
            'Projeto Informático',
            'Seminário',
            'Inovação e Empreendedorismo',
            'Tópicos Avançados de Engenharia de Software',
            'Desenvolvimento de Aplicações Empresariais',
            'Sistemas de Apoio à Decisão',
            'Engenharia do Conhecimento',
            'Sistemas de Informação Empresariais',
            'Centros de Processamento de Dados',
            'Tópicos Avançados de Redes',
            'Segurança de Sistemas',
            'Laboratório de Tecnologias de Informação',
            'Engenharia de Sistemas e Serviços',
            'Direito da Administração Pública (de Portugal e de Macau)',
            'Ciência Política',
            'Políticas Públicas (em Portugal e em Macau)',
            'Gestão de Recursos Humanos na Administração Pública',
            'Análise de Dados',
            'Metodologia da Investigação Científica',
            'Direito Administrativo Especial (de Portugal e de Macau)',
            'Contratação Pública (em Portugal e em Macau)',
            'Políticas Sócio-Económicas na Ásia-Pacífico',
            'Liderança e Negociação',
            'Sistemas e Tecnologias de Informação',
            'Políticas e Análise de Risco na Segurança de Informação',
            'Segurança em Redes de Computadores',
            'Análise Forense Digital I',
            'Administração Segura de Sistemas Informáticos',
            'Projeto de Segurança I',
            'Laboratório de Testes de Penetração',
            'Gestão e Análise de Relatórios de Segurança',
            'Tratamento de Incidentes de Segurança Informática',
            'Análise Forense Digital II',
            'Projeto de Segurança II',
            'Contabilidade e Finanças',
            'Gestão Estratégica Avançada',
            'Métodos Quantitativos de Gestão',
            'Controlo de Gestão e Controlo Interno',
            'Gestão do Conhecimento e Qualidade',
            'Sistemas de Controlo de Gestão',
            'Contabilidade e Análise de Valor',
            'Instrumentos de Controlo de Gestão',
            'Gestão de Projectos',
            'Auditoria Estratégica',
            'Gestão e Avaliação do Risco',
            'Avaliação de Activos',
            'Aquisição e Controlo de Empresas',
            'Governo das Sociedades e Responsabilidade Social.Optimização e Controlo',
            'Negócios e Estratégia Financeira',
            'Relato Contabilístico',
            'Desenvolvimento e Comportamento de Motores',
            'Instrumentação e Processamento de Sinais',
            'Vibrações, Ruído e Conforto',
            'Engenharia Assistida em Projecto de Veículos',
            'Organização e Gestão Automóvel',
            'Factor Humano na Empresa',
            'Impacto, Deformação e Segurança em Veículos',
            'Energia e Reciclagem nos Transportes',
            'Comunicação nos Veículos',
            'Tecnologias Avançadas em Produção de Veículos',
            'Legislação e Conflito',
            'Marketing Aplicado ao Negócio Automóvel',
            'Análise Dinâmica e Engenharia Sísmica',
            'Construção e Manutenção de Pavimentos',
            'Hidráulica Urbana',
            'Revestimentos e Acabamentos',
            'Construção Sustentável',
            'Segurança e Qualidade em Obras e Projectos',
            'Estruturas de Madeira e de Alvenaria',
            'Modelação e Avaliação de Estruturas',
            'Conforto Ambiental em Edifícios',
            'Avaliação Imobiliária e Manutenção das Construções',
            'Estruturas Metálicas e Mistas',
            'Planeamento e Gestão da Mobilidade',
            'Segurança Contra Incêndios',
            'Sistemas de Tratamento de Águas',
            'Métodos de Decisão e Optimização',
            'Termofluidos',
            'Políticas de Gestão Ambiental',
            'Política Energética e Desenvolvimento Sustentável',
            'Avaliação de Parâmetros Ambientais',
            'Gestão da Qualidade do Ar',
            'Gestão da Qualidade da Água',
            'Gestão de Resíduos',
            'Planeamento e Ordenamento do Território',
            'Energia e Ambiente nos Transportes',
            'Utilização Racional de Energia',
            'Climatização',
            'Tecnologia das Energias Renováveis',
            'Avaliação de Impactes Ambientais',
            'Compatibilidade Eletromagnética e Certificação',
            'Otimização e Aprendizagem Automática',
            'Introdução à Investigação',
            'Sistemas Rádio',
            'Codificação de Áudio e Vídeo',
            'Eletrónica de Alta Frequência',
            'Sistemas de Comunicações Multimédia',
            'Eletrónica Configurável',
            'Antenas e Radiopropagação',
            'Sistemas Avançados de Controlo',
            'Sistemas Elétricos de Energia',
            'Acionamentos em Sistemas Automáticos',
            'Transitórios e Qualidade de Energia',
            'Robótica Avançada',
            'Aplicações das Energias Renováveis',
            'Visão Computacional',
            'Desenvolvimento de Aplicações Multiplataforma',
            'Automação Inteligente e a Indústria 4.0',
            'Desenvolvimento para Dispositivos Móveis',
            'Interfaces para Ambientes Ubíquos',
            'Tecnologias e Serviços de Nova Geração',
            'Cibersegurança',
            'Gestão de Projetos Informáticos',
            'Mobilidade em Sistemas Computacionais',
            'Sistemas Sensíveis ao Contexto',
            'Computação em Nuvem',
            'Desenvolvimento de Jogos para Dispositivos Móveis',
            'Arquiteturas Empresariais',
            'Qualidade de Software',
            'Segurança Ofensiva em Sistemas Ubíquos',
            'Análise Forense em Dispositivos Móveis',
        ];

        $anoLetivo = [
            "2016/2017",
            "2017/2018",
            "2018/2019",
            "2019/2020",
            "2020/2021",
        ];

        $cursos = DB::table('curso')->pluck('id')->toArray();
        $createdAt = Carbon\Carbon::now()->subDays(30);
        $l = 0;
        foreach ($disciplinas as $disciplina) {
            $l = $l + 1;
            DB::table('unidadecurricular')->insert([
                'nome' => $disciplina,
                'semestre' => $faker->randomElement(["1", "2"]),
                'ano' => $faker->randomElement(["1", "2", "3", "4"]),
                'anoLetivo' =>$faker->randomElement($anoLetivo),
                'curso_id' => $faker->randomElement($cursos),
                'estado' => $faker->randomElement(["0", "1"]),
                'created_at' => $createdAt,
                'updated_at' => $createdAt,
            ]);
        }
        $this->command->info("UnidadeCurricular seeder - Finish");
    }
}
